THRESHOLD_DETECT = 0.4
THRESHOLD_COVERAGE = 0.5

ICS_URL = "http://192.168.1.30:7000/ics/taskOrder/addTask"  # Replace with actual URL
PROCESSING_LOOP_DELAY = 1  # seconds

# Snapshot configuration
ENABLE_SNAPSHOTS = False
SNAPSHOT_DIR = "snapshots"
SNAPSHOT_QUALITY = 95  # JPEG quality (0-100)

USE_GPU_DECODE = True
GPU_DECODE_BUFFER_SIZE = 10**6  # 1MB buffer for subprocess pipe
FFMPEG_RECONNECT_DELAY = 1.0    # seconds
FFMPEG_MAX_RETRIES = 5

INFERENCE_MAX_QUEUE_SIZE = 500
INFERENCE_MAX_BATCH_SIZE = 32
INFERENCE_BATCH_TIMEOUT = 1 
INFERENCE_NUM_STREAMS = 3
MODEL_PATH = "models/ModelHN_160326_02.engine"
END_POINT_EMPTY = "end_10001546"