FROM nvcr.io/nvidia/tensorrt:24.02-py3

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    API_URL=http://api_server:5000

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_worker.txt /app/requirements_worker.txt

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements_worker.txt

COPY . /app

CMD ["python3", "-m", "worker.main_worker"]
